### ISSUE TITLE
Zivotopis - odsazeni <p /> tagu + nadbytecne mezery

### ISSUE THREAD

**Issue by TomasProkes** [kamivan/Zivotopis#1]
Ahoj Ivano,
životopis máš hezky zpracovaný, díky.
Snad jen pár drobností:  Některé značky máš nesprávně zarovnané, např. tento odstavec by měl být o 1 úroveň více zanořený:
https://github.com/kamivan/Zivotopis/blob/43400358b92d55f62af564f0692d176c2e37d3f7/index.html#L29

A občas máš v kódu zbytečné mezery navíc, např. zde na řádcích 34 až 37:
https://github.com/kamivan/Zivotopis/blob/43400358b92d55f62af564f0692d176c2e37d3f7/index.html#L34

Až budeš mít čas, můžeš si tyto drobnosti opravit, případně ještě přidat navigační lištu s odkazy na jednotlivé sekce (tak jak je ukázáno v lekci 10 z Luďkova Úvodu do HTML/CSS v materiálech z první lekce).

Děkuji a přeji krásný den.
T.

**Comment by kamivan** [comment]
Ahoj, dekuji za komentar, trosku jsem jeste poopravila.
